// method + modifier + ingredient + product = awesome new Michelin star-worthy recipe

let textComponents = {
    "methods": {
        "default": [
            "",
            "Ash-coated",
            "Barbecued",
            "Beer-battered",
            "Blowtorched",
            "Braised",
            "Candied",
            "Caramelised",
            "Cherry-wood smoked",
            "Cold-smoked",
            "Compressed",
            "Confit",
            "Deconstructed",
            "Deep-fried",
            "Dehydrated",
            "Flame-grilled",
            "Free-range",
            "Freeze-dried",
            "Gluten-free",
            "Hand-cut",
            "Herb-crusted",
            "Hot-smoked",
            "Jellied",
            "Outdoor-reared",
            "Panko-breaded",
            "Pickled",
            "Poached",
            "Raw",
            "Roasted",
            "Salt-baked",
            "Sautéed",
            "Seared",
            "Slow-roasted",
            "Smoked",
            "Sous-vide",
            "Spherified",
            "Spiralised",
            "Stone-baked",
            "Tempura",
            "Textures of",
            "Thinly sliced",
            "Triple-cooked",
            "Vegan",
            "Vegetarian",
            "Whipped",
            // Add new items at the end to prevent links breaking
        ],
        "xmas": [
            "",
            "Ash-coated",
            "Beer-battered",
            "Blowtorched",
            "Braised",
            "Candied",
            "Caramelised",
            "Cold-smoked",
            "Compressed",
            "Confit",
            "Deconstructed",
            "Deep-fried",
            "Dehydrated",
            "Free-range",
            "Freeze-dried",
            "Gluten-free",
            "Hand-cut",
            "Herb-crusted",
            "Hot-smoked",
            "Jellied",
            "Outdoor-reared",
            "Panko-breaded",
            "Pickled",
            "Poached",
            "Raw",
            "Roasted",
            "Salt-baked",
            "Sautéed",
            "Seared",
            "Slow-roasted",
            "Smoked",
            "Sous-vide",
            "Tempura",
            "Textures of",
            "Thinly sliced",
            "Triple-cooked",
            "Vegan",
            "Vegetarian",
            "Whipped",
            // Add new items at the end to prevent links breaking
        ]
    },
    "modifiers":{
        "default": [
            "",
            "Aged",
            "Artisan",
            "Artisanal",
            "Biodynamic",
            "British",
            "Dry-aged",
            "Dry-cured",
            "Foraged",
            "Grass-fed",
            "Hand-dived",
            "Heirloom",
            "Heritage",
            "Line-caught",
            "Moroccan spiced",
            "New season",
            "Organic",
            "Rare-breed",
            "Sustainable",
            "Thai-inspired",
            // Add new items at the end to prevent links breaking
        ],
        "xmas": [
            "",
            "Aged",
            "Artisan",
            "Artisanal",
            "British",
            "Dry-aged",
            "Dry-cured",
            "Festive",
            "Foraged",
            "Grass-fed",
            "Heirloom",
            "Heritage",
            "Organic",
            "Rare-breed",
            "Sustainable",
            "Whiskey-infused",
            // Add new items at the end to prevent links breaking
        ]
    },
    "ingredients": {
        "default": [
            "",
            "Ant",
            "Beef fat",
            "Black garlic",
            "Black truffle",
            "Blonde caramel",
            "Bloody mary",
            "Bone marrow",
            "Brioche",
            "Brussels sprout",
            "Buckwheat",
            "Calf's liver",
            "Candied bacon",
            "Cauliflower",
            "Chicken",
            "Chicken breast",
            "Chicken feet",
            "Chive",
            "Chive flower",
            "Clam",
            "Cock's comb",
            "Cod cheek",
            "Cucumber",
            "Duck breast",
            "Duck egg",
            "Duck fat",
            "Duck leg",
            "Earl Grey tea",
            "Eel",
            "Egg yolk",
            "Espresso martini",
            "Faux gras",
            "Fennel",
            "Fennel pollen",
            "Focaccia",
            "Foie gras",
            "Frog legs",
            "Game chips",
            "Gin and tonic",
            "Goose fat",
            "Green tomato",
            "Guinea fowl",
            "Hamburger",
            "Kohlrabi",
            "Lamb neck",
            "Langoustine",
            "Lentil",
            "Locust",
            "Mackerel",
            "Market fish",
            "Marmite",
            "Mars bar",
            "Megrim",
            "Miso",
            "Mushroom",
            "Mussel",
            "Octopus",
            "Olive",
            "Olive oil",
            "Otoro",
            "Oxtail",
            "Ox tongue",
            "Oyster",
            "Oyster mushroom",
            "Parsnip",
            "Pheasant",
            "Pig's trotter",
            "Pork belly",
            "Pornstar martini",
            "Poulet de Bresse",
            "Prosecco",
            "Pumpkin spice",
            "Puy lentil",
            "Quail egg",
            "Rainbow carrot",
            "Roasted yeast",
            "Rib-eye steak",
            "Rose veal",
            "Salmon fillet",
            "Salsify",
            "Salted caramel",
            "Samphire",
            "Scallop",
            "Sea bass",
            "Sea herb",
            "Shitake mushroom",
            "Skate wing",
            "Sole",
            "Squab",
            "Squid",
            "Sriracha",
            "Sweetbread",
            "Tofu",
            "Tripe",
            "Turbot",
            "Venison",
            "Wagyu beef",
            "Whitebait",
            "White chocolate",
            "Whole salmon",
            "Wood pigeon",
            // Add new items at the end to prevent links breaking
            "Celeriac",
        ],
        "xmas": [
            "",
            "Baileys",
            "Beef fat",
            "Black garlic",
            "Black truffle",
            "Blonde caramel",
            "Bloody mary",
            "Bone marrow",
            "Brandy",
            "Brussels sprout",
            "Candied bacon",
            "Chestnut",
            "Cranberry",
            "Cranberry & orange",
            "Duck breast",
            "Duck egg",
            "Duck fat",
            "Duck leg",
            "Earl Grey tea",
            "Egg yolk",
            "Espresso martini",
            "Foie gras",
            "Gammon",
            "Gin and tonic",
            "Goose",
            "Goose fat",
            "Guinea fowl",
            "Unbranded Irish cream liqueur",
            "Kevin the Carrot",
            "Parsnip",
            "Pheasant",
            "Pornstar martini",
            "Port",
            "Prosecco",
            "Reindeer",
            "Sage & onion",
            "Tofurkey",
            "Turducken",
            "Turkey",
            "Venison",
            "Walnut",
            "Whiskey",
            "White chocolate",
            "Whole ham",
            "Whole salmon",
            // Add new items at the end to prevent links breaking
        ]
    },
    "products": {
        "default": [
            "Ballotine",
            "Beurre noisette",
            "Broth",
            "Ceviche",
            "Cheesecake",
            "Chips",
            "Consommé",
            "Crêpe",
            "Crisps",
            "Crumb",
            "Crème brûlée",
            "Custard",
            "Eggnog",
            "En gelée",
            "En papillote",
            "En-croute",
            "Espuma",
            "Five ways",
            "Foam",
            "Fondant",
            "Fondue",
            "French fries",
            "Gel",
            "Gnocchi",
            "Granola",
            "Gravy",
            "Ice cream",
            "In aspic",
            "In a basket",
            "In a sesame seed bun",
            "Infusion",
            "Jus",
            "Ketchup",
            "Mayonnaise",
            "Meringue",
            "Mille-feuille",
            "Mince pie",
            "Mousse",
            "Nachos",
            "Omelette",
            "On a buttery biscuit base",
            "On toast",
            "Pancake",
            "Panna cotta",
            "Pâté",
            "Pie",
            "Pigs in blankets",
            "Pithivier",
            "Popcorn",
            "Potato fondant",
            "Quiche",
            "Ragout",
            "Ragù",
            "Ravioli",
            "Raviolo",
            "Reduction",
            "Roullade",
            "Sandwich",
            "Sauce",
            "Sausage",
            "Sorbet",
            "Soufflé",
            "Sourdough",
            "Stew",
            "Tacos",
            "Tart",
            "Tartlet",
            "Tartare",
            "Tea",
            "Terrine",
            "Three ways",
            "Toast",
            "Velouté",
            "Vol-au-vent",
            "Wensleydale",
            // Add new items at the end to prevent links breaking
            "Puree",
        ],
        "xmas": [
            "Baubles",
            "Butter",
            "Christmas cake",
            "Christmas crackers",
            "Christmas pudding",
            "Chutney",
            "Covered in glitter",
            "Crisps",
            "Crème brûlée",
            "Eggnog",
            "Filo pastry parcels",
            "Gin",
            "Gravy",
            "Ice cream",
            "In a sparkly box",
            "In red and green packaging",
            "Ketchup",
            "Liqueur",
            "Mayonnaise",
            "Mince pies",
            "Mini scotch eggs",
            "Pâté",
            "Pie",
            "Pigs in blankets",
            "Popcorn",
            "Prawn ring",
            "Roullade",
            "Sandwich",
            "Sauce",
            "Sausage",
            "Sausage rolls",
            "Soufflé",
            "Stuffing balls",
            "Tart",
            "Three bird roast",
            "Three ways",
            "Toast",
            "Vodka",
            "Vol-au-vents",
            "Wensleydale",
            "With a picture of Santa on the box",
            "Wrapped in bacon",
            // Add new items at the end to prevent links breaking
        ]
    },
    "critiques": {
        "default": [
            // No persistent links here (yet) so keep it alphabetical for ease of maintenance
            "\"A bit rushed\"",
            "\"An unusual flavour combination\"",
            "\"Challenging\"",
            "\"Claggy\"",
            "\"Faultless\"",
            "\"Flabby\"",
            "\"I can't eat that\"",
            "\"Inedible\"",
            "\"Messy\"",
            "\"Not for me\"",
            "\"Poor plating\"",
            "\"Raw\"",
            "\"Restaurant-worthy\"",
            "\"Totally raw\"",
            "\"Ugly\"",
            "\"Un-rendered fat\"",
            "\"Under-cooked\"",
            "\"Under-seasoned\""
        ]
    }
}