// method + modifier + ingredient + product = awesome new Michelin star-worthy recipe

let methods = [
    "",
    "Barbecued",
    "Beer-battered",
    "Blowtorched",
    "Braised",
    "Candied",
    "Caramelised",
    "Cherry-wood smoked",
    "Cold-smoked",
    "Compressed",
    "Deconstructed",
    "Deep-fried",
    "Dehydrated",
    "Flame-grilled",
    "Free-range",
    "Freeze-dried",
    "Gluten-free",
    "Hand-cut",
    "Hot-smoked",
    "Outdoor-reared",
    "Panko-breaded",
    "Pickled",
    "Poached",
    "Raw",
    "Roasted",
    "Salt-baked",
    "Sautéed",
    "Slow-roasted",
    "Smoked",
    "Sous-vide",
    "Spherified",
    "Spiralised",
    "Stone-baked",
    "Tempura",
    "Textures of",
    "Thinly sliced",
    "Triple-cooked",
    "Vegan",
    "Vegetarian",
    "Whipped"
]

let modifiers = [
    "",
    "Aged",
    "Artisan",
    "Artisanal",
    "Ash-coated",
    "Biodynamic",
    "British",
    "Dry-aged",
    "Dry-cured",
    "Foraged",
    "Grass-fed",
    "Hand-dived",
    "Heirloom",
    "Heritage",
    "Jellied",
    "Line-caught",
    "New season",
    "Organic",
    "Rare-breed",
    "Sustainable"
]

let ingredients = [
    "",
    "Ant",
    "Beef fat",
    "Black truffle",
    "Blonde caramel",
    "Bloody mary",
    "Bone marrow",
    "Brussels sprouts",
    "Buckwheat",
    "Calf's liver",
    "Candied bacon",
    "Cauliflower",
    "Chicken",
    "Chicken breast",
    "Chicken feet",
    "Chive",
    "Chive flower",
    "Clam",
    "Cock's comb",
    "Cod cheek",
    "Cucumber",
    "Duck breast",
    "Duck egg",
    "Duck leg",
    "Earl Grey tea",
    "Eel",
    "Egg yolk",
    "Espresso martini",
    "Faux gras",
    "Fennel",
    "Fennel pollen",
    "Focaccia",
    "Foie gras",
    "Frog legs",
    "Gin and tonic",
    "Green tomato",
    "Guinea fowl",
    "Hamburger",
    "Kohlrabi",
    "Lamb neck",
    "Langoustine",
    "Lentil",
    "Locust",
    "Mackerel",
    "Market fish",
    "Marmite",
    "Mars bar",
    "Megrim",
    "Miso",
    "Mushroom",
    "Mussel",
    "Octopus",
    "Olive",
    "Olive oil",
    "Otoro",
    "Oxtail",
    "Ox tongue",
    "Oyster",
    "Oyster mushroom",
    "Parsnip",
    "Pheasant",
    "Pig's trotter",
    "Pork belly",
    "Pornstar martini",
    "Poulet de Bresse",
    "Prosecco",
    "Pumpkin spice",
    "Puy lentil",
    "Quail egg",
    "Rainbow carrot",
    "Roasted yeast",
    "Rib-eye steak",
    "Rose veal",
    "Salmon fillet",
    "Salsify",
    "Salted caramel",
    "Samphire",
    "Scallop",
    "Sea herb",
    "Shitake mushroom",
    "Skate wing",
    "Sole",
    "Squab",
    "Squid",
    "Sriracha",
    "Sweetbreads",
    "Tripe",
    "Turbot",
    "Venison",
    "Wagyu beef",
    "Whitebait",
    "White chocolate",
    "Whole salmon",
    "Wood pigeon"
]

let products = [
    "Beurre noisette",
    "Broth",
    "Ceviche",
    "Chips",
    "Consommé",
    "Crêpe",
    "Crisps",
    "Crumb",
    "Crème brûlée",
    "Custard",
    "Eggnog",
    "En gelée",
    "En papillote",
    "En-croute",
    "Espuma",
    "Five ways",
    "Foam",
    "Fondant",
    "Fondue",
    "French fries",
    "Gel",
    "Gnocchi",
    "Granola",
    "Gravy",
    "Ice cream",
    "In aspic",
    "In a basket",
    "In a sesame seed bun",
    "Jus",
    "Ketchup",
    "Mayonnaise",
    "Meringue",
    "Mille-feuille",
    "Mince pie",
    "Mousse",
    "Nachos",
    "Omelette",
    "Pancake",
    "Panna cotta",
    "Pâté",
    "Pie",
    "Pigs in blankets",
    "Pithivier",
    "Popcorn",
    "Ragout",
    "Ragù",
    "Ravioli",
    "Raviolo",
    "Reduction",
    "Roullade",
    "Sandwich",
    "Sauce",
    "Sorbet",
    "Soufflé",
    "Sourdough",
    "Stew",
    "Tart",
    "Tartare",
    "Tea",
    "Terrine",
    "Three ways",
    "Toast",
    "Velouté",
    "Vol-au-vent",
    "Wensleydale"
]